#!/usr/bin/env python3
# -*-coding :utf-8 -*-

import re
import sys
import os
import cmp
import comm
import argparse

parser = argparse.ArgumentParser(description="Run test cases with specified parameters.")
parser.add_argument("-tc", help="Specify the test case name (tc_name).", type=str)
parser.add_argument("-mode", help="Specify the simulation mode (tc_mode).", type=str)
parser.add_argument("-wave", help="Specify the wave name.", type=str)
parser.add_argument("-cfg", help="Specify the configuration file.", type=str)
parser.add_argument("-skipc", help="Skip compilation step.", action="store_true")
parser.add_argument("-help", help="Show help information.", action="store_true")

args = parser.parse_args()
all_cfg = ''
rst_cfg = ''

if args.tc:
    tc_name = args.tc
if args.mode:
    tc_mode = args.mode + '/'
if args.wave:
    tc_wave = args.wave
if args.cfg:
    all_cfg = all_cfg + comm.get_sim_cfg(args.cfg)
if args.skipc:
    skipc = 1

cmp_cmd = cmp.get_cmp_cmd()
run_cmd = './simv -ucli -do wave.do +fsdbfile+'+ tc_mode +tc_name +'.fsdb'+' +UVM_TESTNAME='+ tc_name +' >'+ tc_mode +tc_name + '.log' + ' ' + all_cfg + ' ' +rst_cfg

def main():
    if skipc == 0 :
        os.system(cmp_cmd)
        os.system(run_cmd)
    else:
        os.system(run_cmd)               

if __name__ == "__main__":
    main()